vegaprotocol/vegawallet-browser

.github/workflows/approbation.yml

first pass at getting approbation reported back to PR
Could be a little nicer in terms of formatting and info given back but there will be nicer handling of csv files if I use a javascript lib and make this into a gh action down the line.

add approbation check

---

.github/workflows/approbation.yml
test/e2e/onboarding.test.ts

Just dump main approbation metrics into the PR so we can compare.

Dump main approbation metrics for comparison

---

jest.config-e2e.js
test/e2e/driver.ts
test/e2e/network.test.ts
test/e2e/settings.test.ts
test/e2e/view-wallet.test.ts
test/e2e/wallet-helpers/api-helpers.ts

Use test set up for configuration of the UI. Faster and more stable than always configuring via UI elements.

Use API Helper for test set up

---

test/e2e/extension-state.test.ts
test/e2e/network.test.ts
test/e2e/onboarding.test.ts
test/e2e/settings.test.ts
test/e2e/view-wallet.test.ts

to correspond with this change https://github.com/vegaprotocol/specs/pull/1712/files

update spec nums

---

.github/workflows/e2e-tests.yml
web-extension/common/background.js

Reduce memory and itterations in encryption to speed up test run

test: speed up tests

---

package.json
rollup/plugins/ajv/index.js
rollup/plugins/manifest/index.js
rollup/postbuild.js
rollup/prebuild.js
yarn.lock

Watch was not working for the copy plugin. This fixes that problem.

chore: fix copy watch

---

frontend/contexts/json-rpc/json-rpc-provider.spec.tsx
frontend/contexts/json-rpc/json-rpc-provider.tsx
frontend/lib/client-rpc-methods.ts
frontend/routes/auth/connections/connection-list.tsx
frontend/routes/auth/connections/connections.spec.tsx
frontend/routes/auth/connections/index.tsx
frontend/stores/connections.spec.tsx
frontend/stores/connections.ts
lib/json-rpc-server.js
lib/port-server.js
package.json
web-extension/backend/admin-ns.js
web-extension/backend/connections.js
yarn.lock

Feat: connection store notification

---

web-extension/background.js
web-extension/pow-worker.js

@dexturr @dalebennett1992 We want to consider this one together. I now remove the code that clears all storage on update. It means we actually have to think about whether there are breaking changes introduced between versions

Feat: Cleanup

---

frontend/contexts/json-rpc/json-rpc-provider.tsx
lib/port-server.js
web-extension/backend/popup-client.js
web-extension/background.js
web-extension/test/popup-client.spec.js

This will make the little badge on the extension icon count only if user interaction is required

fix: move setPending count to client popup

---

frontend/components/connection-modal/connection-details.spec.tsx
frontend/components/loading-button/index.tsx
frontend/components/transaction-modal/transaction-modal.spec.tsx
frontend/index.css
frontend/routes/auth/connections/connections.spec.tsx
frontend/routes/auth/settings/settings.spec.tsx
frontend/routes/auth/wallets/wallets.spec.tsx
frontend/routes/login/index.tsx
frontend/routes/login/login.spec.tsx
frontend/routes/onboarding/create-password/create-password.spec.tsx
frontend/routes/onboarding/create-password/index.tsx
frontend/routes/onboarding/import-wallet/import-wallet.spec.tsx
frontend/routes/onboarding/import-wallet/index.tsx
frontend/routes/onboarding/save-mnemonic/index.tsx
frontend/routes/onboarding/save-mnemonic/save-mnemonic.spec.tsx
frontend/test-helpers/mock-client.ts
test/e2e/connect-wallet.test.ts
test/e2e/extension-state.test.ts
test/e2e/list-connections.test.ts
test/e2e/login.test.ts
test/e2e/network.test.ts
test/e2e/onboarding.test.ts
test/e2e/settings.test.ts
test/e2e/transaction.test.ts
test/e2e/view-wallet.test.ts

While the app is encrypting it can be slow, the buttons to continue should be disabled and show a loading state.
Related to #263

feat: disabled buttons and add loading states

---

frontend/components/connection-modal/connection-success.tsx
frontend/components/icons/success-tick.tsx
frontend/components/stars-wrapper/index.tsx
frontend/components/stars-wrapper/stars-wrapper.spec.tsx
frontend/components/vega-header/index.tsx
frontend/components/vega-header/vega-header.spec.tsx
frontend/routes/login/index.tsx
frontend/routes/onboarding/get-started/index.tsx
frontend/routes/onboarding/import-wallet/import-wallet.spec.tsx
frontend/routes/onboarding/import-wallet/index.tsx
frontend/routes/onboarding/import-wallet/wallet-imported.tsx
frontend/routes/onboarding/save-mnemonic/index.tsx
frontend/routes/onboarding/save-mnemonic/save-mnemonic.spec.tsx
frontend/routes/onboarding/save-mnemonic/wallet-created.tsx
test/e2e/onboarding.test.ts
test/e2e/page-objects/import-a-wallet.ts
test/e2e/page-objects/secure-your-wallet.ts
test/jest-config/jest.config-e2e.js

Related to #194 
Give user feedback when a wallet is created or imported successfully.

feat: create/import wallets success state

---

frontend/components/key-icon/index.tsx
frontend/components/key-icon/key-icon.spec.tsx
frontend/setupTests.ts
package.json
yarn.lock

feat: new icons

---

frontend/components/connection-modal/connection-details.spec.tsx
frontend/components/connection-modal/connection-details.tsx

chore: update copy

---

frontend/components/icons/error.tsx
package.json
yarn.lock

UI toolkit was throwing errors in tests, bumping the version fixes these errors
Some properties were kebab case instead of camel case causing more errors, remove these as well

test: reduce noise in tests

---

frontend/components/mnemonic-container/index.tsx
frontend/routes/login/index.tsx
frontend/routes/login/login.spec.tsx
frontend/routes/onboarding/create-password/create-password.spec.tsx
frontend/routes/onboarding/create-password/index.tsx
frontend/routes/onboarding/create-wallet/create-wallet.spec.tsx
frontend/routes/onboarding/create-wallet/index.tsx
frontend/routes/onboarding/get-started/get-started.spec.tsx
frontend/routes/onboarding/get-started/index.tsx
frontend/routes/onboarding/import-wallet/import-wallet.spec.tsx
frontend/routes/onboarding/import-wallet/index.tsx
frontend/routes/onboarding/save-mnemonic/save-mnemonic.spec.tsx
frontend/routes/onboarding/telemetry/index.tsx
frontend/routes/onboarding/telemetry/telemetry.spec.tsx

feat: onboarding with keyboard alone

---

frontend/routes/onboarding/telemetry/index.tsx
frontend/routes/onboarding/telemetry/telemetry.spec.tsx

Related to [383](https://github.com/vegaprotocol/vegawallet-browser/issues/383)

chore: change copy on button

---

frontend/components/connection-modal/connection-details.tsx
frontend/components/splash/splash.tsx
frontend/components/transaction-modal/index.tsx
frontend/routes/auth/index.tsx

fix: icon size

---

frontend/components/error-modal/index.tsx

chore: use error.stack instead of message

---

.github/dependabot.yml

Bump @vegaprotocol/* dependencies automatically

chore: auto bump dependencies

---

.github/workflows/add_issue_to_project.yml

update project manage action secret

chore: update project manage action secret

---

frontend/components/copy-with-check/copy-with-check.spec.tsx
frontend/contexts/json-rpc/json-rpc-context.ts

chore: import parts of react needed rather than everything

---

frontend/contexts/json-rpc/json-rpc-provider.spec.tsx
frontend/contexts/json-rpc/json-rpc-provider.tsx
frontend/hooks/redirect-path/index.tsx
frontend/hooks/redirect-path/redirect-path.spec.tsx
frontend/hooks/suggest-mnemonic/index.ts
frontend/lib/create-wallet.ts
frontend/lib/extension-apis.ts
frontend/locator-ids.ts
frontend/routes/onboarding/import-wallet/import-wallet.spec.tsx
frontend/routes/onboarding/save-mnemonic/index.tsx
frontend/routes/onboarding/save-mnemonic/save-mnemonic-form.spec.tsx
frontend/routes/onboarding/save-mnemonic/save-mnemonic-form.tsx
frontend/routes/onboarding/save-mnemonic/save-mnemonic.spec.tsx
frontend/routes/onboarding/save-mnemonic/use-persisted-suggest-mnemonic.ts
frontend/test-helpers/mock-client.ts
frontend/test-helpers/mock-storage.ts
test/e2e/extension-state.spec.ts
test/e2e/page-objects/secure-your-wallet.ts

Persist recovery phrase while user is onboarding and the wallet is not yet create.
Related to: #292

feat: persist recovery phrase

---

.eslintrc.json
frontend/components/page-header/page-header.spec.tsx
frontend/hooks/sentry/index.tsx
frontend/hooks/sentry/sentry.spec.tsx
frontend/lib/config.d.ts
frontend/lib/config.ts
frontend/lib/logging.tsx
frontend/routes/auth/settings/settings.spec.tsx
frontend/routes/auth/settings/telemetry-section.spec.tsx
frontend/routes/auth/settings/telemetry-section.tsx
frontend/routes/auth/wallets/index.tsx
frontend/routes/onboarding/telemetry/index.tsx
frontend/routes/onboarding/telemetry/telemetry.spec.tsx
rollup/backend.js
rollup/frontend.js
test/jest-config/jest.config-backend.js
test/jest-config/jest.config-e2e.js
test/jest-config/jest.config-ui.js
web-extension/background.js

Alias with non-reserved character in npm

chore: alias with non-reserved character

---

frontend/App.spec.tsx
frontend/App.tsx
frontend/hooks/ping/index.tsx
frontend/hooks/ping/ping.spec.tsx
lib/mv3-keep-alive.js

chore: create keep alive hook

---

config/mainnet.js
config/test.js
config/testnet.js
frontend/components/dapps-header/dapps-header.spec.tsx
frontend/components/dapps-header/dapps-header.tsx
frontend/lib/config.d.ts
frontend/routes/auth/auth.spec.tsx
frontend/routes/auth/index.tsx
frontend/routes/auth/wallets/wallets-header.tsx
frontend/setupTests.ts
package.json
specs/1106-KEYS-wallet_and_keys.md
yarn.lock

feat: calls to actions to trade or govern

---

README.md

Add docs for current browser support

docs: add browser support

---

frontend/routes/auth/connections/connection-list.tsx

style: fix cross height

---

config/mainnet.js
config/test.js
config/testnet.js
frontend/components/icons/info.tsx
frontend/components/modals/transaction-modal/transaction-modal.tsx
frontend/components/navbar/navbar.tsx
frontend/components/receipts/transfer/index.tsx
frontend/components/receipts/transfer/transfer.spec.tsx
frontend/components/receipts/utils/amount-with-tooltip.spec.tsx
frontend/components/receipts/utils/amount-with-tooltip.tsx
frontend/components/receipts/utils/price-with-symbol.spec.tsx
frontend/components/receipts/utils/price-with-symbol.tsx
frontend/components/splash/splash.tsx
frontend/hooks/prevent-window-resize/index.tsx
frontend/index.css
frontend/lib/config.d.ts
lib/constants.js
specs/1114-RCPT-receipt_views.md
web-extension/backend/windows.js
web-extension/test/admin-ns.spec.js

Show amount in transfer screen with tooltip to explain how this can be calculated to the exact amount.

feat: show transfer amount

---

frontend/components/receipts/transfer/index.tsx

fix: minor visual bug from conflicts

---

.github/workflows/e2e-tests.yml
.github/workflows/wallet-with-console-smoke.yml
config/console-smoke.js
package.json
rollup.config.js
test/console-smoke/console-smoke.spec.ts
test/console-smoke/console.ts
test/e2e/helpers/selenium-util.ts
test/e2e/helpers/wallet/common-wallet-values.ts
test/e2e/helpers/wallet/wallet-api.ts
test/jest-config/jest.config-console-smoke.js
test/jest-config/jest.config-e2e.js

Add smoke test with fairground. Checks that from fairground we can connect to a wallet and send a transaction. We approve connections and transactions from the browser wallet and check for success on the console. Docker deployment of console included.

Smoke test wallet with console testnet

---

config/console-smoke.js
config/dev.js
config/mainnet.js
config/test.js
config/testnet.js
frontend/lib/config.d.ts
specs/1113-POPT-auto-popout.md
web-extension/background.js
web-extension/lib/setup-listeners.js
web-extension/lib/setup-listeners.spec.js

Related to #403 
Video triggers "install" event by reloading the extension, this is the same event that is triggered when a user installs the extension.
https://github.com/vegaprotocol/vegawallet-browser/assets/26136207/3f058045-1eed-43e0-a5a8-351788ffb9e1

feat: auto open on install

---

frontend/lib/logging.tsx

Logging was not behaving in dev mode, this fixes that.

fix: logging was not working correctly

---

frontend/components/receipts/batch-market-instructions/batch-market-instructions.spec.tsx
frontend/components/receipts/batch-market-instructions/batch-market-instructions.tsx

Batch market instructions, if some fields were not provided, were causing issues

fix: batch market instructions

---

frontend/components/receipts/transfer/transfer.spec.tsx
frontend/components/receipts/transfer/transfer.tsx
frontend/lib/utils.spec.ts
frontend/lib/utils.ts

feat: fix bad transaction rendering

---

frontend/components/copy-with-check/copy-with-check.spec.tsx

Reduce warnings in copy-with-check component

Reduce test warnings

---

package.json
yarn.lock

Remove a bunch of build warnings from unmet peer dependencies.

chore: remove plethora of build warnings

---

package.json
specs/1118-ORDS-submit_order.md
specs/1126-VKEY-vega_key.md

Prettier was not being run on spec files and it supports md file so this PR introduces that and fixes all exsiting issues 😄

Run prettier on specs

---

frontend/components/receipts/transfer/enriched-transfer-view.spec.tsx
frontend/components/receipts/utils/order-table.spec.tsx
frontend/components/receipts/utils/order-table.tsx
frontend/components/receipts/utils/order/build-order-columns.spec.tsx
frontend/components/receipts/utils/order/build-order-columns.tsx
frontend/components/receipts/utils/order/order-price.spec.tsx
frontend/components/receipts/utils/order/order-size.spec.tsx
frontend/components/receipts/utils/order/order-size.tsx
frontend/components/receipts/utils/order/pegged-order-info.spec.tsx
frontend/components/receipts/utils/string-amounts/amount-with-symbol.spec.tsx
frontend/components/receipts/utils/string-amounts/amount-with-symbol.tsx

Order size should not have any units, it's in contracts not base asset

fix: order size units

---

frontend/components/header/header.tsx
frontend/components/keys/vega-key/index.tsx
frontend/components/pages/page/page.tsx
frontend/lib/client-rpc-methods.ts
frontend/routes/auth/wallets/home/wallets.spec.tsx
frontend/routes/auth/wallets/home/wallets.tsx
frontend/routes/auth/wallets/index.spec.tsx
frontend/routes/auth/wallets/index.tsx
frontend/routes/auth/wallets/key-details/export-private-key-dialog/export-private-key-form.tsx
frontend/routes/auth/wallets/key-details/key-details-page.spec.tsx
frontend/routes/auth/wallets/key-details/key-details-page.tsx
frontend/routes/auth/wallets/key-details/rename-key-dialog/index.tsx
frontend/routes/auth/wallets/key-details/rename-key-dialog/rename-key-dialog.spec.tsx
frontend/routes/auth/wallets/key-details/rename-key-dialog/rename-key-dialog.tsx
frontend/routes/auth/wallets/key-details/rename-key-dialog/rename-key-form.spec.tsx
frontend/routes/auth/wallets/key-details/rename-key-dialog/rename-key-form.tsx
frontend/routes/routes.tsx
frontend/stores/wallets.ts
specs/1125-KEYD-key_details.md

feat: rename UI

---

frontend/components/receipts/apply-referral-code/apply-referral-code.spec.tsx
frontend/components/receipts/apply-referral-code/apply-referral-code.tsx
frontend/components/receipts/apply-referral-code/index.tsx
frontend/components/receipts/transaction-map.tsx
frontend/lib/transactions.ts
scripts/generate-transactions-map.js
specs/1131-ARFR-apply_referral_code.md

Closes #451 
Adds support for apply referral code transaction type.
Also added a script to make TX updates easier, haven't fully automated as this is unlikely to be a huge time sink but should assist in making these updates when they occur.

chore: referrals view

---

frontend/components/receipts/transfer/basic-transfer-view.spec.tsx
frontend/components/receipts/transfer/basic-transfer-view.tsx
frontend/components/receipts/transfer/enriched-transfer-view.spec.tsx
frontend/components/receipts/transfer/enriched-transfer-view.tsx
frontend/components/receipts/transfer/transfer.spec.tsx
frontend/components/receipts/transfer/transfer.tsx
specs/1124-TRAN-transfer.md

Closes #248 
Render a warning if the key is not recognised by the wallet

feat: render warning if key is external

---

frontend/app.spec.tsx
frontend/app.tsx
frontend/components/modals/orientation-splash/index.tsx
frontend/components/modals/orientation-splash/orientation-splash.spec.tsx

Fixes:
* Mobile splash incorrectly showing on desktop
* Height on Firefox desktop not looking correct

fix: height issues, mobile splash

---

frontend/components/modals/transaction-modal/get-title.spec.ts
frontend/components/modals/transaction-modal/get-title.ts
frontend/hooks/format-size-amount/format-size-amount.spec.tsx
frontend/hooks/format-size-amount/format-size-amount.tsx
frontend/lib/transactions.ts

Closes https://github.com/vegaprotocol/vegawallet-browser/issues/649

fix: position size to display "max"

---

config/mainnet.js
config/testnet.js
frontend/components/page-header/index.tsx
frontend/components/page-header/page-header.spec.tsx

fix: enable popout

---

package.json
web-extension/test/generate-transactions.spec.ts
yarn.lock

Bump protos for Vega version 0.74
Closes #679

chore: bump protos

---

test/README.md
test/console-smoke/README.md
test/e2e/README.md
test/resillience-tests/README.md

test: READMEs

---

frontend/routes/onboarding/get-started/disclaimer.spec.tsx
frontend/routes/onboarding/get-started/disclaimer.tsx

chore: make disclaimer links clickable

---

web-extension/backend/admin-ns.js
web-extension/backend/fetch-cache.js
web-extension/test/fetch-cache.spec.js

Assets cache was network independent which resulted in networks being incorrectly returned.

fix: asset cache

---

frontend/lib/create-wallet.ts
frontend/routes/onboarding/import-wallet/import-wallet.spec.tsx
frontend/routes/onboarding/import-wallet/index.tsx
frontend/stores/wallets.ts
test/console-smoke/console-smoke.spec.ts
test/e2e/helpers/wallet/wallet-api.ts
test/e2e/key-details.spec.ts
test/e2e/onboarding.spec.ts
test/e2e/page-objects/key-details.ts
test/e2e/switch-network.spec.tsx
test/e2e/view-wallet.spec.ts
test/resillience-tests/key-details.spec.tsx
web-extension/backend/wallets.js
web-extension/test/admin-ns.spec.js
web-extension/test/wallets.spec.js

Closes #708 
Generate key 0 when a user creates or imports a wallet

feat: key 0

---

frontend/routes/onboarding/import-wallet/import-wallet.spec.tsx
frontend/routes/onboarding/import-wallet/index.tsx
lib/constants.js
specs/1101-ONBD-onboarding.md
web-extension/backend/wallets.js

feat: permit other length recovery phrases

---

README.md
web-extension/backend/wallets.js
web-extension/background.js
web-extension/test/wallets.spec.js

Add accounts_changed event
Closes #453

Add events in background script for key rename & create

---

ios-app/Vega Wallet/Vega Wallet.xcodeproj/project.pbxproj

chore: make minimum deployment version iOS 16.4 to ensure session.storage exists

---

web-extension/backend/connections.js
web-extension/backend/wallets.js
web-extension/background.js
web-extension/lib/setup-listeners.js
web-extension/test/admin-ns.spec.js
web-extension/test/client-ns.spec.js
web-extension/test/connections.spec.js
web-extension/test/setup-listeners.spec.js
web-extension/test/wallets.spec.js

fix: key order

---

frontend/components/receipts/utils/order/order-price.spec.tsx
frontend/components/receipts/utils/order/order-price.tsx
frontend/components/receipts/utils/order/pegged-order-info.tsx
frontend/hooks/market-settlement-asset/market-settlement-asset.spec.tsx
frontend/hooks/market-settlement-asset/market-settlement-asset.tsx
frontend/lib/markets.spec.ts
frontend/lib/markets.ts
frontend/stores/markets-store.ts

fix: spot markets causing errors on order receipt

---

package.json
web-extension/test/generate-transactions.spec.ts
yarn.lock

chore: bump the protos

---

.github/workflows/gh-release.yml

Generate the release on tag rather that requiring a manual run.

ci: automate GitHub releases

---

frontend/components/receipts/utils/order-table.tsx
frontend/components/receipts/utils/order/side.spec.tsx
frontend/components/receipts/utils/order/side.tsx
frontend/lib/enums/enums.tsx
frontend/lib/markets.ts

feat: render buy sell for spot markets

---

test/mobile/tests/userflows.spec.js
web-extension/backend/client-ns.js

chore: open popup if in ios
